Repository clue2-sose25/Clue2, pull requests merged in 2025-06, with the labels that each got.

#67 Implemented CLUE as service
  .env
  .vscode/launch.json
  Readme.md
  clue_builders/ots/build.py
  clue_deployer/Dockerfile
  clue_deployer/entrypoint.sh
  clue_deployer/patch_kubeconfig.py
  clue_deployer/pyproject.toml
  clue_deployer/service/models.py
  clue_deployer/service/service.py
  clue_deployer/service/status.py
  clue_deployer/service/status_manager.py
  clue_deployer/src/autoscaling_deployer.py
  clue_deployer/src/config/__init__.py
  clue_deployer/src/config/env_config.py
  clue_deployer/src/deploy.py
  clue_deployer/src/experiment.py
  clue_deployer/src/experiment_environment.py
  clue_deployer/src/experiment_list.py
  clue_deployer/src/experiment_results.py
  clue_deployer/src/experiment_runner.py
  clue_deployer/src/experiment_workloads.py
  clue_deployer/src/helm_wrapper.py
  clue_deployer/src/main.py
  clue_deployer/src/run.py
  clue_deployer/src/workload_runner.py
  docker-compose.yml
  kind-config.yaml
Labels: Devops, Backend

#74 More SUT decoupling + logging
  clue-config.yaml
  clue_builders/toystore/Dockerfile
  clue_builders/toystore/build.py
  clue_deployer/service/service.py
  clue_deployer/src/autoscaling_deployer.py
  clue_deployer/src/config/__init__.py
  clue_deployer/src/config/clue_config.py
  clue_deployer/src/config/config.py
  clue_deployer/src/config/env_config.py
  clue_deployer/src/config/experiment_configs.py
  clue_deployer/src/config/helm_replacement.py
  clue_deployer/src/config/sut_config.py
  clue_deployer/src/deploy.py
  clue_deployer/src/experiment_list.py
  clue_deployer/src/helm_wrapper.py
  clue_deployer/src/main.py
  clue_deployer/src/scaling_experiment_setting.py
  sut_configs/ots.yaml
  sut_configs/teastore.yaml
  sut_configs/toystore.yaml
Labels: Backend

#85 Logs dashboard
  clue_dashboard/nginx.conf
  clue_dashboard/src/components/LogsPanel.tsx
  clue_deployer/entrypoint.sh
  clue_deployer/src/logger.py
  clue_deployer/src/models/logs_response.py
  clue_deployer/src/service/service.py
  create-kind-cluster.sh
Labels: Frontend, Backend

#108 Otel demo deployment
  clue_deployer/src/config/helm_dependencies.py
  clue_deployer/src/config/sut_config.py
  clue_deployer/src/deploy.py
  clue_deployer/src/helm_wrapper.py
  sut_configs/otel-demo.yaml
Labels: Devops

#121 New Homepage, Rework Control Panel Page
  clue_webui/src/App.tsx
  clue_webui/src/components/Navbar.tsx
  clue_webui/src/pages/ControlsPage.tsx
  clue_webui/src/pages/DashboardPage.tsx
  clue_webui/src/pages/HomePage.tsx
Labels: Frontend
