Repository clue2-sose25/Clue2, pull requests merged in 2025-07, with the labels that each got.

#132 Extend the functionality of SUTs configs #111
  clue_deployer/src/service/routers/suts.py
  clue_webui/package-lock.json
  clue_webui/package.json
  clue_webui/src/App.tsx
  clue_webui/src/pages/AddSutPage.tsx
  clue_webui/src/pages/ExperimentPage.tsx
  sut_configs/default_sut.yaml
Labels: Frontend, Backend

#164 Finishing results page
  .gitignore
  clue_deployer/pyproject.toml
  clue_deployer/src/experiment_results.py
  clue_deployer/src/models/start_server_request.py
  clue_deployer/src/results/data_analysis.py
  clue_deployer/src/results/experiment_results.py
  clue_deployer/src/service/routers/results.py
  docker-compose.yml
Labels: Devops, Frontend, Backend

#188 Fix estimated time on experiment page
  clue_webui/src/components/experiment/EstimationTime.tsx
  clue_webui/src/models/SUT.ts
Labels: Frontend

#195 Fixing coding steps and Helm Charts improvements
  .env
  .github/actions/clue-docker/action.yml
  .github/actions/clue-docker/action_use_example.txt
  .github/actions/clue-docker/example.txt
  .github/actions/clue-helm/action.yml
  .github/actions/clue-helm/example.txt
  .github/workflows/clue_deploy_toystore_helm.yaml
  Readme.md
  clue_deployer/entrypoint.sh
  clue_deployer/k8s/clue-deployer-job.yaml
  clue_deployer/k8s/clue-deployer-rbac.yaml
  clue_deployer/src/configs/env_config.py
  clue_deployer/src/variant_deployer.py
  clue_helm/templates/clue-deployer-job.yaml
  clue_helm/templates/clue-deployer-service.yaml
  clue_helm/templates/clue-deployer.yaml
  clue_helm/templates/pvc.yaml
  clue_helm/templates/rbac.yaml
  clue_helm/values-otel-demo.yaml
  clue_helm/values-teastore.yaml
  clue_helm/values-toystore.yaml
  clue_helm/values.yaml
Labels: bug, Devops
